apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "triggers.fullname" . }}-controller
  labels:
    {{- include "triggers.baseLabels" . | nindent 4 }}
    {{- include "triggers.helmLabels" . | nindent 4 }}
    {{- include "triggers.versionLabels" . | nindent 4 }}
    {{- include "triggers.componentLabels" "controller" | nindent 4 }}
    {{- include "triggers.nameLabels" "controller" | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "triggers.baseLabels" . | nindent 6 }}
      {{- include "triggers.componentLabels" "controller" | nindent 6 }}
      {{- include "triggers.nameLabels" "controller" | nindent 6 }}
  template:
    metadata:
      {{- with .Values.controller.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "triggers.baseLabels" . | nindent 8 }}
        {{- include "triggers.helmLabels" . | nindent 8 }}
        {{- include "triggers.versionLabels" . | nindent 8 }}
        {{- include "triggers.componentLabels" "controller" | nindent 8 }}
        {{- include "triggers.nameLabels" "controller" | nindent 8 }}
    spec:
      serviceAccountName: {{ template "triggers.serviceAccountName" . }}
      {{- with .Values.controller.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: controller
          image: {{ printf "%s:%s" .Values.controller.image.repository .Values.controller.image.tag | quote }}
          imagePullPolicy: {{ .Values.controller.image.pullPolicy | quote }}
          args:
          {{- range .Values.controller.args }}
            - {{ . | quote }}
          {{- end }}
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG_LOGGING_NAME
              value: {{ template "triggers.fullname" . }}-logging
            - name: CONFIG_OBSERVABILITY_NAME
              value: {{ template "triggers.fullname" . }}-observability
            - name: METRICS_DOMAIN
              value: tekton.dev/triggers
          {{- with .Values.controller.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.controller.metrics.enabled }}
          ports:
            - containerPort: 9090
              protocol: TCP
          {{- end }}
