{{- if .Values.webhook.podDisruptionBudget.enabled }}
{{- if gt (.Values.webhook.replicas | int) 1 }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "triggers.fullname" . }}-webhook
  labels:
    {{- include "triggers.baseLabels" . | nindent 4 }}
    {{- include "triggers.helmLabels" . | nindent 4 }}
    {{- include "triggers.componentLabels" "webhook" | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "triggers.baseLabels" . | nindent 6 }}
      {{- include "triggers.componentLabels" "webhook" | nindent 6 }}
      {{- include "triggers.nameLabels" "webhook" | nindent 6 }}
  {{- if .Values.webhook.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.webhook.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.webhook.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.webhook.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
{{- end }}
