apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ template "triggers.fullname" . }}-validation
  labels:
    {{- include "triggers.baseLabels" . | nindent 4 }}
    {{- include "triggers.helmLabels" . | nindent 4 }}
    {{- include "triggers.componentLabels" "webhook" | nindent 4 }}
webhooks:
  - name: validation.webhook.triggers.tekton.dev
    admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: {{ template "triggers.fullname" . }}-webhook
        namespace: {{ .Release.Namespace }}
    failurePolicy: Fail
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "triggers.fullname" . }}-webhook
  labels:
    {{- include "triggers.baseLabels" . | nindent 4 }}
    {{- include "triggers.helmLabels" . | nindent 4 }}
    {{- include "triggers.componentLabels" "webhook" | nindent 4 }}
webhooks:
  - name: webhook.triggers.tekton.dev
    admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: {{ template "triggers.fullname" . }}-webhook
        namespace: {{ .Release.Namespace }}
    failurePolicy: Fail
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ template "triggers.fullname" . }}-config
  labels:
    {{- include "triggers.baseLabels" . | nindent 4 }}
    {{- include "triggers.helmLabels" . | nindent 4 }}
    {{- include "triggers.componentLabels" "webhook" | nindent 4 }}
webhooks:
  - name: config.webhook.triggers.tekton.dev
    admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: {{ template "triggers.fullname" . }}-webhook
        namespace: {{ .Release.Namespace }}
    failurePolicy: Fail
    sideEffects: None
    objectSelector:
      matchLabels:
        {{- include "triggers.baseLabels" . | nindent 8 }}
