# version -- Tekton pipelines version used to add labels on deployments, pods and services
version:

# nameOverride -- Partially override resource generated names
nameOverride: ''

# fullnameOverride -- Fully override resource generated names
fullnameOverride: ''

rbac:
  # rbac.create -- Create RBAC resources
  create: true

  # rbac.controllerServiceAccount -- Name of the service account to use for controller when rbac.create is false
  controllerServiceAccount:

  # rbac.webhookServiceAccount -- Name of the service account to use for webhook when rbac.create is false
  webhookServiceAccount:

podSecurityPolicy:
  # podSecurityPolicy.enabled -- Enable pod security policy
  enabled: false

config:
  # config.artifactBucket -- Configuration for artifact bucket (see https://github.com/tektoncd/pipeline/blob/master/docs/install.md)
  # @default -- See [values.yaml](./values.yaml)
  artifactBucket: {}
  #    # location of the gcs bucket to be used for artifact storage
  #    location: "gs://bucket-name"
  #    # name of the secret that will contain the credentials for the service account
  #    # with access to the bucket
  #    bucket.service.account.secret.name:
  #    # The key in the secret with the required service account json
  #    bucket.service.account.secret.key:

  # config.artifactPvc -- Configuration for artifact pvc (see https://github.com/tektoncd/pipeline/blob/master/docs/install.md)
  # @default -- See [values.yaml](./values.yaml)
  artifactPvc: {}
  #   # size of the PVC volume
  #   size: 5Gi
  #
  #   # storage class of the PVC volume
  #   storageClassName: storage-class-name


  # config.defaults -- Configuration for default values (see https://github.com/tektoncd/pipeline/blob/master/docs/install.md)
  # @default -- See [values.yaml](./values.yaml)
  defaults:
    _example: |-
      ################################
      #                              #
      #    EXAMPLE CONFIGURATION     #
      #                              #
      ################################

      # This block is not actually functional configuration,
      # but serves to illustrate the available configuration
      # options and document them in a way that is accessible
      # to users that `kubectl edit` this config map.
      #
      # These sample configuration options may be copied out of
      # this example block and unindented to be in the data block
      # to actually change the configuration.

      # default-timeout-minutes contains the default number of
      # minutes to use for TaskRun and PipelineRun, if none is specified.
      default-timeout-minutes: "60"  # 60 minutes

      # default-service-account contains the default service account name
      # to use for TaskRun and PipelineRun, if none is specified.
      default-service-account: "default"

      # default-managed-by-label-value contains the default value given to the
      # "app.kubernetes.io/managed-by" label applied to all Pods created for
      # TaskRuns. If a user's requested TaskRun specifies another value for this
      # label, the user's request supercedes.
      default-managed-by-label-value: "tekton-pipelines"

      # default-pod-template contains the default pod template to use
      # TaskRun and PipelineRun, if none is specified. If a pod template
      # is specified, the default pod template is ignored.
      # default-pod-template:

      # default-cloud-events-sink contains the default CloudEvents sink to be
      # used for TaskRun and PipelineRun, when no sink is specified.
      # Note that right now it is still not possible to set a PipelineRun or
      # TaskRun specific sink, so the default is the only option available.
      # If no sink is specified, no CloudEvent is generated
      # default-cloud-events-sink:

  # config.featureFlags -- Configuration for feature flags
  # @default -- See [values.yaml](./values.yaml)
  featureFlags:
    # Setting this flag to "true" will prevent Tekton to create an
    # Affinity Assistant for every TaskRun sharing a PVC workspace
    #
    # The default behaviour is for Tekton to create Affinity Assistants
    #
    # See more in the workspace documentation about Affinity Assistant
    # https://github.com/tektoncd/pipeline/blob/master/docs/workspaces.md#affinity-assistant-and-specifying-workspace-order-in-a-pipeline
    # or https://github.com/tektoncd/pipeline/pull/2630 for more info.
    disable-affinity-assistant: "false"
    # Setting this flag to "true" will prevent Tekton overriding your
    # Task container's $HOME environment variable.
    #
    # The default behaviour currently is for Tekton to override the
    # $HOME environment variable but this will change in an upcoming
    # release.
    #
    # See https://github.com/tektoncd/pipeline/issues/2013 for more
    # info.
    disable-home-env-overwrite: "false"
    # Setting this flag to "true" will prevent Tekton overriding your
    # Task container's working directory.
    #
    # The default behaviour currently is for Tekton to override the
    # working directory if not set by the user but this will change
    # in an upcoming release.
    #
    # See https://github.com/tektoncd/pipeline/issues/1836 for more
    # info.
    disable-working-directory-overwrite: "false"
    # This option should be set to false when Pipelines is running in a
    # cluster that does not use injected sidecars such as Istio. Setting
    # it to false should decrease the time it takes for a TaskRun to start
    # running. For clusters that use injected sidecars, setting this
    # option to false can lead to unexpected behavior.
    #
    # See https://github.com/tektoncd/pipeline/issues/2080 for more info.
    running-in-environment-with-injected-sidecars: "true"

  # config.leaderElection -- Configuration for leader election
  # @default -- See [values.yaml](./values.yaml)
  leaderElection:
    # An inactive but valid configuration follows; see example.
    resourceLock: "leases"
    leaseDuration: "15s"
    renewDeadline: "10s"
    retryPeriod: "2s"

  # config.logging -- Configuration for logging (see https://github.com/tektoncd/pipeline/blob/master/docs/install.md)
  # @default -- See [values.yaml](./values.yaml)
  logging:
    # Common configuration for all knative codebase
    zap-logger-config: |
      {
        "level": "info",
        "development": false,
        "sampling": {
          "initial": 100,
          "thereafter": 100
        },
        "outputPaths": ["stdout"],
        "errorOutputPaths": ["stderr"],
        "encoding": "json",
        "encoderConfig": {
          "timeKey": "",
          "levelKey": "level",
          "nameKey": "logger",
          "callerKey": "caller",
          "messageKey": "msg",
          "stacktraceKey": "stacktrace",
          "lineEnding": "",
          "levelEncoder": "",
          "timeEncoder": "",
          "durationEncoder": "",
          "callerEncoder": ""
        }
      }
    # Log level overrides
    loglevel.controller: "info"
    loglevel.webhook: "info"

  # config.observability -- Configuration for observability (see https://github.com/tektoncd/pipeline/blob/master/docs/install.md)
  # @default -- See [values.yaml](./values.yaml)
  observability:
    _example: |
      ################################
      #                              #
      #    EXAMPLE CONFIGURATION     #
      #                              #
      ################################

      # This block is not actually functional configuration,
      # but serves to illustrate the available configuration
      # options and document them in a way that is accessible
      # to users that `kubectl edit` this config map.
      #
      # These sample configuration options may be copied out of
      # this example block and unindented to be in the data block
      # to actually change the configuration.

      # metrics.backend-destination field specifies the system metrics destination.
      # It supports either prometheus (the default) or stackdriver.
      # Note: Using Stackdriver will incur additional charges.
      metrics.backend-destination: prometheus

      # metrics.stackdriver-project-id field specifies the Stackdriver project ID. This
      # field is optional. When running on GCE, application default credentials will be
      # used and metrics will be sent to the cluster's project if this field is
      # not provided.
      metrics.stackdriver-project-id: "<your stackdriver project id>"

      # metrics.allow-stackdriver-custom-metrics indicates whether it is allowed
      # to send metrics to Stackdriver using "global" resource type and custom
      # metric type. Setting this flag to "true" could cause extra Stackdriver
      # charge.  If metrics.backend-destination is not Stackdriver, this is
      # ignored.
      metrics.allow-stackdriver-custom-metrics: "false"

controller:
  image:
    # controller.image.repository -- Controller docker image repository
    repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller

    # controller.image.tag -- Controller docker image tag
    tag:

    # controller.image.pullPolicy -- Controller docker image pull policy
    pullPolicy: IfNotPresent

  # controller.annotations -- Controller pod annotations
  # @default -- See [values.yaml](./values.yaml)
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'

  # controller.nodeSelector -- Controller node selector
  nodeSelector: {}

  # controller.affinity -- Controller affinity rules
  affinity: {}

  # controller.tolerations -- Controller tolerations
  tolerations: []

  # controller.resources -- Controller resource limits and requests
  resources: {}

  # controller.securityContext -- Controller pods security context
  securityContext: {}

  # controller.args -- Controller arguments
  # @default -- See [values.yaml](./values.yaml)
  args:
    - -kubeconfig-writer-image
    - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter:v0.14.2
    - -creds-image
    - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/creds-init:v0.14.2
    - -git-image
    - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.14.2
    - -nop-image
    - tianon/true@sha256:009cce421096698832595ce039aa13fa44327d96beedb84282a69d3dbcf5a81b
    - -shell-image
    - gcr.io/distroless/base@sha256:f79e093f9ba639c957ee857b1ad57ae5046c328998bf8f72b30081db4d8edbe4
    - -gsutil-image
    - google/cloud-sdk@sha256:37654ada9b7afbc32828b537030e85de672a9dd468ac5c92a36da1e203a98def
    - -entrypoint-image
    - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.14.2
    - -imagedigest-exporter-image
    - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter:v0.14.2
    - -pr-image
    - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/pullrequest-init:v0.14.2
    - -build-gcs-fetcher-image
    - gcr.io/tekton-releases/github.com/tektoncd/pipeline/vendor/github.com/googlecloudplatform/cloud-builders/gcs-fetcher/cmd/gcs-fetcher:v0.14.2
    - -affinity-assistant-image
    - nginx@sha256:c870bf53de0357813af37b9500cb1c2ff9fb4c00120d5fe1d75c21591293c34d

  service:
    # controller.service.type -- Controller service type
    type: ClusterIP

    # controller.service.annotations -- Controller service annotations
    annotations: {}

  metrics:
    # controller.metrics.enabled -- Enable controller metrics service
    enabled: true

    # controller.metrics.port -- Controller metrics service port
    port: 9090

    # controller.metrics.service.portName -- Controller metrics service port name
    portName: metrics

webhook:
  image:
    # webhook.image.repository -- Webhook docker image repository
    repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook

    # webhook.image.tag -- Webhook docker image tag
    tag:

    # webhook.image.pullPolicy -- Webhook docker image pull policy
    pullPolicy: IfNotPresent

  # webhook.replicas -- Webhook replicas
  replicas: 1

  # webhook.annotations -- Webhook pod annotations
  # @default -- See [values.yaml](./values.yaml)
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'

  # webhook.nodeSelector -- Webhook node selector
  nodeSelector: {}

  # webhook.affinity -- Webhook affinity rules
  affinity: {}

  # webhook.tolerations -- Webhook tolerations
  tolerations: []

  # webhook.resources -- Webhook resource limits and requests
  resources: {}

  # webhook.updateStrategy -- Webhook pods update strategy
  updateStrategy: {}

  # webhook.securityContext -- Webhook pods security context
  securityContext: {}

  podDisruptionBudget:
    # webhook.podDisruptionBudget.enabled -- Enable pod disruption budget for webhook
    ennabled: false

    # webhook.podDisruptionBudget.minAvailable -- Minimum available webhook pods
    minAvailable: 1

    # webhook.podDisruptionBudget.maxUnavailable -- Maximum unavailable webhook pods
    maxUnavailable: 1

  service:
    # webhook.service.type -- Webhook service type
    type: ClusterIP

    # webhook.service.annotations -- Webhook service annotations
    annotations: {}

  metrics:
    # webhook.metrics.enabled -- Enable webhook metrics service
    enabled: true

    # webhook.metrics.port -- Webhook metrics service port
    port: 9090

    # webhook.metrics.portName -- Webhook metrics service port name
    portName: http-metrics

  profiling:
    # webhook.profiling.enabled -- Enable pebhook profiling service
    enabled: true

    # webhook.profiling.port -- Webhook profiling service port
    port: 8008

    # webhook.profiling.portName -- Webhook profiling service port name
    portName: http-profiling
