{{- if .Values.rbac.create }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "pipelines.fullname" . }}
  labels:
    {{- include "pipelines.baseLabels" . | nindent 4 }}
    {{- include "pipelines.helmLabels" . | nindent 4 }}
rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - limitranges
      - pods/log
      - namespaces
      - secrets
      - events
      - serviceaccounts
      - configmaps
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
  - apiGroups: 
      - apps
    resources: 
      - deployments
    verbs: 
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
  - apiGroups: 
      - apps
    resources: 
      - deployments/finalizers
    verbs: 
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
  - apiGroups: 
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
    verbs: 
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
  - apiGroups: 
      - tekton.dev
    resources: 
      - tasks
      - clustertasks
      - taskruns
      - pipelines
      - pipelineruns
      - pipelineresources
      - conditions
    verbs: 
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
  - apiGroups: 
      - tekton.dev
    resources: 
      - taskruns/finalizers
      - pipelineruns/finalizers
    verbs: 
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
  - apiGroups: 
      - tekton.dev
    resources: 
      - tasks/status
      - clustertasks/status
      - taskruns/status
      - pipelines/status
      - pipelineruns/status
      - pipelineresources/status
    verbs: 
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
  {{- if .Values.podSecurityPolicy.enabled }}
  - apiGroups: 
      - policy
    resources: 
      - podsecuritypolicies
    resourceNames: 
      - {{ template "pipelines.fullname" . }}
    verbs: 
      - use
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "pipelines.fullname" . }}-edit
  labels:
    {{- include "pipelines.baseLabels" . | nindent 4 }}
    {{- include "pipelines.helmLabels" . | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-edit: 'true'
    rbac.authorization.k8s.io/aggregate-to-admin: 'true'
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - tasks
      - taskruns
      - pipelines
      - pipelineruns
      - pipelineresources
      - conditions
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "pipelines.fullname" . }}-view
  labels:
    {{- include "pipelines.baseLabels" . | nindent 4 }}
    {{- include "pipelines.helmLabels" . | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-view: 'true'
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - tasks
      - taskruns
      - pipelines
      - pipelineruns
      - pipelineresources
      - conditions
    verbs:
      - get
      - list
      - watch
{{- end }}
