{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "pipelines.fullname" . }}
  labels:
    {{- include "pipelines.baseLabels" . | nindent 4 }}
    {{- include "pipelines.helmLabels" . | nindent 4 }}
    {{- include "pipelines.componentLabels" "controller" | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "pipelines.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "pipelines.controllerServiceAccount" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
