{{- if .Values.rbac.create }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "pipelines.fullname" . }}
  labels:
    {{- include "pipelines.baseLabels" . | nindent 4 }}
    {{- include "pipelines.helmLabels" . | nindent 4 }}
    {{- include "pipelines.componentLabels" "controller" | nindent 4 }}
rules:
  - apiGroups:
      - ''
    # Namespace access is required because the controller timeout handling logic
    # iterates over all namespaces and times out any PipelineRuns that have expired.
    # Pod access is required because the taskrun controller wants to be updated when
    # a Pod underlying a TaskRun changes state.
    resources:
      - namespaces
      - pods
    verbs:
      - list
      - watch
    # Controller needs cluster access to all of the CRDs that it is responsible for
    # managing.
  - apiGroups:
      - tekton.dev
    resources:
      - tasks
      - clustertasks
      - taskruns
      - pipelines
      - pipelineruns
      - pipelineresources
      - conditions
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
  - apiGroups:
      - tekton.dev
    resources:
      - taskruns/finalizers
      - pipelineruns/finalizers
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
  - apiGroups:
      - tekton.dev
    resources:
      - tasks/status
      - clustertasks/status
      - taskruns/status
      - pipelines/status
      - pipelineruns/status
      - pipelineresources/status
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
  {{- if .Values.podSecurityPolicy.enabled }}
  - apiGroups: 
      - policy
    resources: 
      - podsecuritypolicies
    resourceNames: 
      - {{ template "pipelines.fullname" . }}
    verbs: 
      - use
  {{- end }}
{{- end }}
