{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pipeline.serviceAccountName" . }}
  labels:
    {{- include "pipeline.baseLabels" . | nindent 4 }}
    {{- include "pipeline.helmLabels" . | nindent 4 }}
{{- end }}
