apiVersion: v1
kind: Secret
metadata:
  name: webhook-certs
  labels:
    {{- include "pipeline.baseLabels" . | nindent 4 }}
    {{- include "pipeline.helmLabels" . | nindent 4 }}
    {{- include "pipeline.componentLabels" "webhook" | nindent 4 }}
