apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.webhook.pipeline.tekton.dev
  labels:
    {{- include "pipelines.baseLabels" . | nindent 4 }}
    {{- include "pipelines.baseLabels" . | nindent 4 }}
    {{- include "pipelines.componentLabels" "webhook" | nindent 4 }}
webhooks:
  - name: validation.webhook.pipeline.tekton.dev
    admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: {{ template "pipelines.fullname" . }}-webhook
        namespace: {{ .Release.Namespace }}
    failurePolicy: Fail
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook.pipeline.tekton.dev
  labels:
    {{- include "pipelines.baseLabels" . | nindent 4 }}
    {{- include "pipelines.helmLabels" . | nindent 4 }}
    {{- include "pipelines.componentLabels" "webhook" | nindent 4 }}
webhooks:
  - name: webhook.pipeline.tekton.dev
    admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: {{ template "pipelines.fullname" . }}-webhook
        namespace: {{ .Release.Namespace }}
    failurePolicy: Fail
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: config.webhook.pipeline.tekton.dev
  labels:
    {{- include "pipelines.baseLabels" . | nindent 4 }}
    {{- include "pipelines.helmLabels" . | nindent 4 }}
    {{- include "pipelines.componentLabels" "webhook" | nindent 4 }}
webhooks:
  - name: config.webhook.pipeline.tekton.dev
    admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: {{ template "pipelines.fullname" . }}-webhook
        namespace: {{ .Release.Namespace }}
    failurePolicy: Fail
    sideEffects: None
    objectSelector:
      matchLabels:
        {{- include "pipelines.baseLabels" . | nindent 8 }}
