name: Pull docs

on: pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Check docs
        run: |
          set -euo pipefail

          docker run --rm -v ${PWD}:/work -w /work jnorwood/helm-docs:v0.12.0

          OUTOFDATE=$(git status --porcelain)

          if [ ! -z "$OUTOFDATE" ]; then
              echo "helm charts doc is out of date, please run `helm-docs` to generate the new docs before pushing your changes"

              exit 1
          fi

          exit 0
